import { randomUUID } from 'node:crypto';
import { join } from 'node:path';
import { TaskAgentRouter } from './task-agents.mjs';
import { SemanticTaskRouter } from './semantic-router.mjs';
import { LocalFeatureEmbeddingProvider } from './local-embedding.mjs';
import { Pe3TaskRegistry } from './registry.mjs';

const MAX_TRANSACTIONS=128, MAX_ATTACHMENTS=16, MAX_ATTACHMENT_NAME=240, MAX_MIME=128;
const DECISIVE_SCORE_FLOOR=.55, DECISIVE_MARGIN=.08;
const RETURN_CUES=['go back to','return to','back to','resume the','resume that','previous task','earlier task'];

export class Pe3ProjectRouter {
  #projectId; #projectRoot; #db; #tst; #router; #semantic; #registry; #transactions=new Map(); #ready; #stats={sequence:0,continuations:0,created:0,reactivated:0,switches:0,localizationQueries:0,localizationHits:0,semanticEscalations:0,semanticFallbacks:0,semanticFailures:0,lastAction:null,lastReason:null};
  constructor({ projectId, projectRoot, projectStore, db, tst, embeddingProvider, semanticRouter, now=Date.now }) {
    this.#projectId=projectId;this.#projectRoot=projectRoot;this.#db=db;this.#tst=tst;this.#router=new TaskAgentRouter({now});this.#semantic=semanticRouter??new SemanticTaskRouter(embeddingProvider??new LocalFeatureEmbeddingProvider());this.#registry=new Pe3TaskRegistry(projectStore??join(process.cwd(),'.cuppet-pe3',String(projectId)),projectRoot);this.#ready=this.#restore();
  }
  async ready(){await this.#ready;}
  status(){return{projectId:this.#projectId,active:this.#router.active,agents:this.#router.list(),stats:{...this.#stats},pendingTransactions:this.#transactions.size,semanticModelID:this.#semantic.modelID};}
  async prepare({sourceSessionId,prompt,attachments=[]}){
    await this.#ready;const source=this.#db.getSessionSummary(sourceSessionId);if(!source||source.projectId!==this.#projectId)throw new Error('PE3 source session is not part of this project');const text=String(prompt??'').trim();if(!text)throw new Error('PE3 prompt is required');const safeAttachments=normalizeAttachments(attachments);let active=this.#router.activate(sourceSessionId);if(!active)active=this.#router.register(sourceSessionId,'',{});
    let route;if(active.turns===0)route={action:'continue',agent:active,reason:'first turn seeds the active task agent',affinity:emptyAffinity()};else route=this.#router.route(text,attachmentEvidence(safeAttachments));
    const explicitReturn=isExplicitReturnPrompt(text);
    if(explicitReturn&&route.action==='create')route={action:'continue',agent:this.#router.active,reason:'explicit return has no deterministic dormant match; escalate conservatively before creating',affinity:route.affinity??emptyAffinity(),semanticEligible:false};
    let evidence=attachmentEvidence(safeAttachments);
    if(route.action==='continue'&&route.semanticEligible&&this.#tst?.configured){this.#stats.localizationQueries++;const localized=await localize(this.#tst,sourceSessionId,text);if(localized.localizedPaths?.length||localized.localizedSymbols?.length){this.#stats.localizationHits++;evidence=mergeEvidence(evidence,localized);route=this.#router.route(text,evidence);}}
    const semanticReturnOnly=route.action==='continue'&&explicitReturn;
    if(route.action==='continue'&&(route.semanticEligible||semanticReturnOnly)){this.#stats.semanticEscalations++;const current=this.#router.active;const dormant=this.#router.list().filter((agent)=>agent.id!==current?.id);if(current){const decision=await this.#semantic.decide(semanticText(text,safeAttachments),current,dormant);if(decision.error)this.#stats.semanticFailures++;if(decision.fallback)this.#stats.semanticFallbacks++;if(decision.action==='reactivate'&&decision.agent)route={action:'reactivate',agent:decision.agent,reason:decision.reason,affinity:route.affinity,refreshPaths:[...decision.agent.stalePaths]};else if(decision.action==='create'&&!semanticReturnOnly)route={action:'create',reason:decision.reason,affinity:route.affinity};else route={...route,reason:decision.action==='create'&&semanticReturnOnly?'explicit return had no decisive dormant semantic match; preserve the active task':decision.reason,semanticEligible:false};}}
    const targetSessionId=route.action==='continue'?sourceSessionId:route.action==='reactivate'?route.agent.sessionID:`session_${randomUUID()}`;const token=`pe3_${randomUUID()}`;const tx={token,state:'prepared',projectId:this.#projectId,sourceSessionId,targetSessionId,action:route.action,reason:route.reason,affinity:route.affinity??emptyAffinity(),refreshPaths:route.action==='reactivate'?[...(route.refreshPaths??[])]:[],prompt:text,attachments:safeAttachments,evidence,createdAt:Date.now()};this.#transactions.set(token,tx);this.#trimTransactions();return publicTx(tx);
  }
  accept(token,{targetAvailable=()=>true}={}){const tx=this.#requireTx(token,'prepared');if(tx.action!=='create'){const target=this.#db.getSessionSummary(tx.targetSessionId);if(!target||target.projectId!==this.#projectId)throw new Error('PE3 target session is unavailable');}for(const pending of this.#transactions.values()){if(pending.token!==tx.token&&pending.state==='accepted'&&pending.targetSessionId===tx.targetSessionId)throw new Error('PE3 target session is busy');}if(!targetAvailable(tx.targetSessionId))throw new Error('PE3 target session is busy');tx.state='accepted';return publicTx(tx);}
  async commit(token,apply){const tx=this.#requireTx(token,'accepted');let result;try{result=apply(tx);}catch(error){tx.state='aborted';this.#transactions.delete(token);throw error;}if(tx.action==='create')this.#router.register(tx.targetSessionId,'',tx.evidence);else this.#router.activate(tx.targetSessionId);this.#router.recordTurn(tx.prompt,tx.evidence);tx.state='committed';this.#transactions.delete(token);this.#record(tx);await this.#save().catch(()=>undefined);return{route:publicTx(tx),result};}
  abort(token,reason='handoff aborted'){const tx=this.#transactions.get(token);if(!tx)return{aborted:false};tx.state='aborted';tx.abortReason=String(reason).slice(0,240);this.#transactions.delete(token);return{aborted:true,route:publicTx(tx)};}
  async noteObservedPaths(sessionID,paths){await this.#ready;this.#router.recordSessionEvidence(sessionID,{activePaths:paths});this.#router.acknowledgeRefresh(sessionID,paths);await this.#save().catch(()=>undefined);}
  async noteWorkspaceMutation(sessionID,paths){await this.#ready;this.#router.recordSessionEvidence(sessionID,{activePaths:paths,touchedPaths:paths});this.#router.noteWorkspaceChange(paths);this.#router.acknowledgeRefresh(sessionID,paths);await this.#save().catch(()=>undefined);}
  async #restore(){const valid=new Set(this.#db.listSessions({projectId:this.#projectId}).map((session)=>session.id));const loaded=await this.#registry.load(valid);for(const agent of loaded.agents)this.#router.restore(agent);if(loaded.activeSessionID)this.#router.select(loaded.activeSessionID);if(loaded.recoveredFromCorruption||loaded.droppedSessionCount)await this.#save().catch(()=>undefined);}
  async #save(){const active=this.#router.active;await this.#registry.save(this.#router.list(),active?.sessionID);}
  #requireTx(token,state){const tx=this.#transactions.get(token);if(!tx||tx.state!==state)throw new Error(`PE3 route token is not ${state}`);return tx;}
  #record(tx){this.#stats.sequence++;if(tx.action==='continue')this.#stats.continuations++;if(tx.action==='create')this.#stats.created++;if(tx.action==='reactivate')this.#stats.reactivated++;if(tx.action!=='continue')this.#stats.switches++;this.#stats.lastAction=tx.action;this.#stats.lastReason=tx.reason;}
  #trimTransactions(){while(this.#transactions.size>MAX_TRANSACTIONS)this.#transactions.delete(this.#transactions.keys().next().value);}
}

export function withRefreshHint(prompt,paths){if(!paths?.length)return prompt;return['[PE3 task resume]','The workspace changed while this task was dormant.',`Before relying on prior file-specific assumptions, refresh these paths from current workspace truth: ${paths.slice(0,12).join(', ')}`,'Do not assume their previous contents are still current.','',prompt].join('\n');}
export function normalizeAttachments(values){if(!Array.isArray(values))return[];return values.slice(0,MAX_ATTACHMENTS).flatMap((item)=>{if(!item||typeof item!=='object')return[];const name=String(item.name??'').trim().slice(0,MAX_ATTACHMENT_NAME),mime=String(item.mime??item.type??'').trim().slice(0,MAX_MIME),path=typeof item.path==='string'?item.path.trim().slice(0,512):'';if(!name&&!path)return[];if(mime&&!/^(?:application|audio|font|image|message|model|multipart|text|video)\/[A-Za-z0-9][A-Za-z0-9!#$&^_.+-]{0,127}$/i.test(mime))return[];return[{...(name?{name}:{}),...(mime?{mime}:{}),...(path?{path}:{}),...(Number.isFinite(item.size)?{size:Math.max(0,Math.trunc(item.size))}:{})}];});}
function attachmentEvidence(attachments){const paths=attachments.flatMap((item)=>item.path?[item.path]:[]);return paths.length?{activePaths:paths}:{};}
function semanticText(prompt,attachments){if(!attachments.length)return prompt;return`${prompt}\nattachments: ${attachments.map((a)=>[a.name,a.path,a.mime].filter(Boolean).join(' ')).join('; ')}`;}
function isExplicitReturnPrompt(prompt){const normalized=String(prompt).toLowerCase().replace(/\s+/g,' ').trim();return RETURN_CUES.some((cue)=>normalized.includes(cue));}
async function localize(tst,sessionID,prompt){const result=await tst.call('memory.query',{session_id:sessionID,query:prompt,limit:12}).catch(()=>({}));const graph=(Array.isArray(result?.graph)?result.graph:[]).filter((item)=>item?.node).sort((a,b)=>score(b)-score(a));if(!graph.length)return{};const top=score(graph[0]),runner=graph[1]?score(graph[1]):undefined,margin=runner===undefined?top:top-runner,decisive=top>=DECISIVE_SCORE_FLOOR&&margin>=DECISIVE_MARGIN;const localization={topScore:top,...(runner!==undefined?{runnerUpScore:runner}:{}),decisive,reason:decisive?'graph localization cleared absolute score and winner-margin thresholds':top<DECISIVE_SCORE_FLOOR?'graph localization top score is below the hard-evidence floor':'graph localization winner margin is too small for hard evidence'};if(!decisive)return{localization};const selected=graph.filter((item,index)=>index===0||score(item)>=top*.55).slice(0,10);return{localization,localizedPaths:unique(selected.flatMap((item)=>typeof item.node.path==='string'?[item.node.path]:[]),6),localizedSymbols:unique(selected.flatMap((item)=>typeof item.node.name==='string'?[item.node.name]:[]),8)};}
function score(item){return typeof item?.score==='number'&&Number.isFinite(item.score)?Math.max(0,item.score):0;}
function unique(values,limit){const out=[],seen=new Set();for(const raw of values){const value=String(raw).trim(),key=value.toLowerCase();if(!value||seen.has(key))continue;seen.add(key);out.push(value);if(out.length>=limit)break;}return out;}
function mergeEvidence(a,b){return{...a,...b,activePaths:[...(a.activePaths??[]),...(b.activePaths??[])],touchedPaths:[...(a.touchedPaths??[]),...(b.touchedPaths??[])],recentSymbols:[...(a.recentSymbols??[]),...(b.recentSymbols??[])],localizedPaths:[...(a.localizedPaths??[]),...(b.localizedPaths??[])],localizedSymbols:[...(a.localizedSymbols??[]),...(b.localizedSymbols??[])]};}
function publicTx(tx){return{token:tx.token,state:tx.state,projectId:tx.projectId,sourceSessionId:tx.sourceSessionId,targetSessionId:tx.targetSessionId,action:tx.action,reason:tx.reason,affinity:{...tx.affinity},refreshPaths:[...tx.refreshPaths],attachments:tx.attachments.map((a)=>({...a})),...(tx.abortReason?{abortReason:tx.abortReason}:{})};}
function emptyAffinity(){return{score:0,pathOverlap:0,symbolOverlap:0,termOverlap:0,lexicalRatio:0,weightedOverlap:0};}