const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('cuppet', {
  health: () => ipcRenderer.invoke('cuppet:health'),
  cognitive: {
    status: () => ipcRenderer.invoke('cuppet:cognitive:status'),
    modeGet: (sessionId) => ipcRenderer.invoke('cuppet:session:mode:get', sessionId),
    modeSet: (sessionId, mode) => ipcRenderer.invoke('cuppet:session:mode:set', sessionId, mode),
    orchestratorSet: (enabled) => ipcRenderer.invoke('cuppet:orchestrator:set', enabled),
    backgroundStatus: () => ipcRenderer.invoke('cuppet:background:status'),
    backgroundPause: () => ipcRenderer.invoke('cuppet:background:pause'),
    backgroundResume: () => ipcRenderer.invoke('cuppet:background:resume'),
    backgroundFlush: (sessionId) => ipcRenderer.invoke('cuppet:background:flush', sessionId),
    planGet: (sessionId, request = { action: 'overview' }) => ipcRenderer.invoke('cuppet:plan:get', sessionId, request),
    memoryQuery: (sessionId, query) => ipcRenderer.invoke('cuppet:memory:query', sessionId, query),
  },
  permissions: {
    list: (sessionId = null) => ipcRenderer.invoke('cuppet:permission:list', sessionId),
    reply: (requestId, reply) => ipcRenderer.invoke('cuppet:permission:reply', requestId, reply),
    autoGet: (sessionId) => ipcRenderer.invoke('cuppet:session:auto:get', sessionId),
    autoSet: (sessionId, enabled) => ipcRenderer.invoke('cuppet:session:auto:set', sessionId, enabled),
  },
  questions: {
    list: (sessionId = null) => ipcRenderer.invoke('cuppet:question:list', sessionId),
    reply: (requestId, answers) => ipcRenderer.invoke('cuppet:question:reply', requestId, answers),
    reject: (requestId) => ipcRenderer.invoke('cuppet:question:reject', requestId),
  },
  remote: {
    status: () => ipcRenderer.invoke('cuppet:remote:status'),
    start: (value = {}) => ipcRenderer.invoke('cuppet:remote:start', value),
    stop: () => ipcRenderer.invoke('cuppet:remote:stop'),
    invite: (role = 'trusted') => ipcRenderer.invoke('cuppet:remote:invite', role),
    devices: () => ipcRenderer.invoke('cuppet:remote:devices'),
    revoke: (deviceId) => ipcRenderer.invoke('cuppet:remote:revoke', deviceId),
  },
  pe3: {
    status: (sessionId) => ipcRenderer.invoke('cuppet:pe3:status', sessionId),
    observePaths: (sessionId, paths) => ipcRenderer.invoke('cuppet:pe3:observe-paths', sessionId, paths),
    workspaceMutation: (sessionId, paths) => ipcRenderer.invoke('cuppet:pe3:workspace-mutation', sessionId, paths),
  },
  sessions: {
    list: (projectId) => ipcRenderer.invoke('cuppet:session:list', projectId),
    create: (projectId = null) => ipcRenderer.invoke('cuppet:session:create', projectId),
    get: (sessionId) => ipcRenderer.invoke('cuppet:session:get', sessionId),
    send: (sessionId, text, attachments = []) => ipcRenderer.invoke('cuppet:session:send', sessionId, text, attachments),
    stop: (sessionId) => ipcRenderer.invoke('cuppet:session:stop', sessionId),
  },
  projects: {
    list: () => ipcRenderer.invoke('cuppet:project:list'),
    get: (projectId) => ipcRenderer.invoke('cuppet:project:get', projectId),
    open: (projectId) => ipcRenderer.invoke('cuppet:project:open', projectId),
    addLocal: (value) => ipcRenderer.invoke('cuppet:project:add-local', value),
    cloneUrl: (value) => ipcRenderer.invoke('cuppet:project:clone-url', value),
    githubList: (query = '') => ipcRenderer.invoke('cuppet:project:github-list', query),
    githubClone: (value) => ipcRenderer.invoke('cuppet:project:github-clone', value),
    relocate: (projectId, path) => ipcRenderer.invoke('cuppet:project:relocate', projectId, path),
    remove: (projectId) => ipcRenderer.invoke('cuppet:project:remove', projectId),
  },
  native: { chooseFolder: (options) => ipcRenderer.invoke('cuppet:native:choose-folder', options) },
  settings: { get: () => ipcRenderer.invoke('cuppet:settings:get'), save: (value) => ipcRenderer.invoke('cuppet:settings:save', value) },
  onEvent: (callback) => { if (typeof callback !== 'function') return () => {}; const listener = (_event, payload) => callback(payload); ipcRenderer.on('cuppet:event', listener); return () => ipcRenderer.removeListener('cuppet:event', listener); },
});
