from pathlib import Path

p = Path('src/main/main.mjs')
s = p.read_text()
old = """async function executeDesktopCommand(request, sessionId, value) {\n  const parsed = typeof value === 'string' ? parseSlashCommand(value) : value;\n  if (parsed?.kind === 'unknown') throw new Error(`Unknown Cuppet command: /${parsed.name}`);\n  if (parsed?.kind !== 'command') throw new Error('A recognized Cuppet command is required');\n  const runtimeCall = (method, params = {}) => request(method, params);\n  const result = await executeCommand(parsed, {\n    sessionId: boundedId(sessionId),\n    call: runtimeCall,\n    providerRequest: settings.runtimeValue(),\n    host: {\n      status: () => request('status', { provider: settings.runtimeValue() }),\n      doctor: () => request('doctor', { provider: settings.runtimeValue() }),\n      remoteStatus: () => request('remote.status'),\n      remoteStart: () => request('remote.start', { setup: true, createInvite: true, provider: settings.runtimeValue() }),\n      remoteStop: () => request('remote.stop'),\n    },\n    provider: desktopProviderAuthority(request),\n  });\n  mainWindow?.webContents.send('cuppet:event', { type: 'command.completed', ...result });\n  return result;\n}\n"""
new = """async function executeDesktopCommand(request, sessionId, value) {\n  const structured = value && typeof value === 'object' && !Array.isArray(value) && typeof value.id === 'string' ? value : null;\n  const parsed = structured\n    ? { kind: 'command', id: boundedId(structured.id), name: null, alias: null, args: [], rawArguments: '', raw: null }\n    : typeof value === 'string' ? parseSlashCommand(value) : value;\n  if (parsed?.kind === 'unknown') throw new Error(`Unknown Cuppet command: /${parsed.name}`);\n  if (parsed?.kind !== 'command') throw new Error('A recognized Cuppet command is required');\n  const runtimeCall = (method, params = {}) => request(method, params);\n  const result = await executeCommand(parsed, {\n    sessionId: boundedId(sessionId),\n    call: runtimeCall,\n    providerRequest: settings.runtimeValue(),\n    host: {\n      status: () => request('status', { provider: settings.runtimeValue() }),\n      doctor: () => request('doctor', { provider: settings.runtimeValue() }),\n      remoteStatus: () => request('remote.status'),\n      remoteStart: () => request('remote.start', { setup: true, createInvite: true, provider: settings.runtimeValue() }),\n      remoteStop: () => request('remote.stop'),\n    },\n    provider: desktopProviderAuthority(request),\n  }, structured ? validateCommandInput(structured.input) : {});\n  mainWindow?.webContents.send('cuppet:event', { type: 'command.completed', ...result });\n  return result;\n}\n"""
if s.count(old) != 1:
    raise SystemExit(f'executeDesktopCommand match count: {s.count(old)}')
s = s.replace(old, new, 1)
marker = "function validateProjectPayload(value) {\n"
helper = """function validateCommandInput(value) {\n  const record = value && typeof value === 'object' && !Array.isArray(value) ? value : {};\n  return {\n    ...(typeof record.key === 'string' ? { key: record.key.trim().slice(0, 240) } : {}),\n    ...(typeof record.value === 'string' ? { value: record.value.trim().slice(0, 4000) } : {}),\n    ...(typeof record.text === 'string' ? { text: record.text.trim().slice(0, 8192) } : {}),\n    ...(['session', 'project', 'global'].includes(record.scope) ? { scope: record.scope } : {}),\n    ...(['plan', 'build'].includes(record.mode) ? { mode: record.mode } : {}),\n    ...(record.pinned === true ? { pinned: true } : {}),\n  };\n}\n\n"""
if s.count(marker) != 1:
    raise SystemExit('validateProjectPayload marker missing')
s = s.replace(marker, helper + marker, 1)
p.write_text(s)
