import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
const root=new URL('..',import.meta.url).pathname;
const paths=['src/runtime/pe3/router.mjs','src/runtime/pe3/registry.mjs','src/runtime/pe3/task-agents.mjs','src/runtime/service.mjs','src/renderer/react/App.tsx','migration/phase-b2-contract.json'];
const text=Object.fromEntries(await Promise.all(paths.map(async p=>[p,await readFile(join(root,p),'utf8')])));const expect=(c,m)=>{if(!c)throw new Error(m)};
const pe3Router=text['src/runtime/pe3/router.mjs'], taskRouter=text['src/runtime/pe3/task-agents.mjs'];
expect(pe3Router.includes('async prepare({sourceSessionId,prompt,attachments=[]})') && pe3Router.includes('this.#router.route(') && taskRouter.includes('route(prompt, evidence = {})'),'PE3 routing surface missing');
expect(text['src/runtime/service.mjs'].includes('pe3.routed'),'runtime PE3 routed event missing');
const app=text['src/renderer/react/App.tsx'];
expect(app.includes("event.type === 'pe3.routed'") && app.includes('event.targetSessionId') && app.includes('openSession(target)'),'React does not follow runtime-selected PE3 target');
expect(app.includes('result?.sessionId') && app.includes('setRunning((current) => new Set(current).add(target))'),'React send path does not follow routed target ownership');
const tests=['test/pe3-task-agents.test.mjs','test/pe3-semantic-router.test.mjs','test/pe3-registry.test.mjs','test/pe3-transaction.test.mjs','test/pe3-reactivation.test.mjs','test/runtime-pe3.test.mjs'];const run=spawnSync(process.execPath,['--test',...tests],{cwd:root,stdio:'inherit'});if(run.status!==0)process.exit(run.status??1);
console.log('Phase B2 gate passed: deterministic/semantic task routing, durable reactivation, transactional handoff, and React target-session following verified.');
