import assert from 'node:assert/strict';
import { access, readFile } from 'node:fs/promises';
import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root=join(dirname(fileURLToPath(import.meta.url)),'..');const read=(p)=>readFile(join(root,p),'utf8');
const pkg=JSON.parse(await read('package.json'));const contract=JSON.parse(await read('migration/e1-contract.json'));const bootstrap=await read('src/main/bootstrap.mjs');const host=await read('src/main/main.mjs');const runtimeClient=await read('src/main/runtime-client.mjs');const credentials=await read('src/main/credential-storage.mjs');const providerSettings=await read('src/main/provider-settings.mjs');const localEmbedding=await read('src/runtime/pe3/local-embedding.mjs');const smoke=await read('scripts/smoke-packaged-runtime.mjs');const ci=await read('.github/workflows/ci.yml');
assert.equal(contract.phase,'E1');for(const [name,value] of Object.entries(contract.requirements))assert.equal(value,true,`E1 requirement not true: ${name}`);assert.equal(contract.runtimeDependencies.npmProductionDependencies,0);
assert.equal(pkg.main,'src/main/bootstrap.mjs');assert.equal(pkg.build.appId,'com.cuppet.desktop');assert.equal(pkg.build.asar,true);assert.deepEqual(pkg.dependencies,{});assert.ok(pkg.build.files.includes('dist-renderer/**/*'));assert.ok(pkg.build.files.includes('src/runtime/**/*'));assert.ok(!pkg.build.files.includes('src/renderer/**/*'));assert.equal(pkg.devDependencies.electron,'44.3.0');assert.ok(pkg.devDependencies.react&&pkg.devDependencies.vite&&pkg.devDependencies.typescript);assert.match(pkg.scripts['pack:dir'],/renderer:verify/);
for(const token of ['requestSingleInstanceLock','setWindowOpenHandler','setPermissionRequestHandler','setPermissionCheckHandler','will-navigate'])assert.match(bootstrap,new RegExp(token));assert.match(host,/dist-renderer.*index\.html/s);assert.match(runtimeClient,/ELECTRON_RUN_AS_NODE: '1'/);assert.match(runtimeClient,/SIGTERM/);assert.match(runtimeClient,/SIGKILL/);assert.match(credentials,/basic_text/);assert.match(providerSettings,/writeSettingsAtomically/);assert.match(providerSettings,/mode: 0o600/);assert.match(localEmbedding,/cuppet\/subword-hash-v1/);assert.doesNotMatch(localEmbedding,/@huggingface|onnxruntime|sharp/i);assert.match(smoke,/app\.asar/);assert.match(smoke,/same data directory/);
assert.match(ci,/workflow_dispatch:/);assert.doesNotMatch(ci,/\n\s*push:/);assert.doesNotMatch(ci,/\n\s*pull_request:/);assert.match(ci,/cancel-in-progress: true/);assert.match(ci,/npm run renderer:verify/);assert.match(ci,/npm run e1:audit-runtime/);assert.match(ci,/npm run pack:dir/);
await assert.rejects(access(join(root,'test/fixtures/runtime-client-child.mjs')),{code:'ENOENT'});
for(const path of ['src/main/bootstrap.mjs','src/main/credential-storage.mjs','src/main/runtime-client.mjs','src/runtime/pe3/local-embedding.mjs','scripts/smoke-packaged-runtime.mjs']){const r=spawnSync(process.execPath,['--check',join(root,path)],{cwd:root,stdio:'inherit'});if(r.status!==0)process.exit(r.status??1)}
const tests=spawnSync(process.execPath,['--test',join(root,'test/e1-packaging.test.mjs'),join(root,'test/pe3-local-embedding.test.mjs')],{cwd:root,stdio:'inherit'});if(tests.status!==0)process.exit(tests.status??1);
console.log('E1 production packaging verification passed with compiled React renderer and manual-only CI.');
