import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
const root=new URL('..',import.meta.url).pathname;const read=(p)=>readFile(join(root,p),'utf8');
const [db,runtimeMain,main,preload,app,sidebar,search,chat,contractText]=await Promise.all(['src/runtime/database.mjs','src/runtime/main.mjs','src/main/main.mjs','src/preload/preload.cjs','src/renderer/react/App.tsx','src/renderer/react/Sidebar.tsx','src/renderer/react/SearchModal.tsx','src/renderer/react/ChatPane.tsx','migration/d1-contract.json'].map(read));const expect=(c,m)=>{if(!c)throw new Error(m)};
expect(db.includes('CREATE VIRTUAL TABLE')&&db.includes('fts5'),'SQLite FTS search missing');expect(runtimeMain.includes("case 'session.search'")&&runtimeMain.includes("case 'session.archive'"),'runtime search/lifecycle authority missing');for(const channel of ['session:search','session:rename','session:archive','session:restore','session:delete','project:rename']){expect(preload.includes(`cuppet:${channel}`),`preload missing ${channel}`);expect(main.includes(`cuppet:${channel}`),`main missing ${channel}`)}
expect(sidebar.includes('Search')&&sidebar.includes('Rename project')&&sidebar.includes('Archive chat')&&sidebar.includes('Delete chat'),'React sidebar lifecycle/search controls missing');expect(app.includes('cuppet.desktop.last-session'),'last-session restoration missing');expect(chat.includes('cuppet.desktop.scroll.'),'per-chat scroll preservation missing');expect(search.includes('sessions.search')&&search.includes('includeArchived')&&search.includes('sessions.restore'),'React search/recovery missing');expect(search.includes('focusMessage(result.itemId)')&&search.includes('scrollIntoView')&&search.includes('search-hit'),'exact search-result message navigation/highlight missing');
const contract=JSON.parse(contractText);for(const value of Object.values(contract.requirements??{}))expect(value===true,'D1 machine contract requirement changed');
const tests=['test/d1-renderer-contract.test.mjs','test/d1-search-lifecycle.test.mjs'];const run=spawnSync(process.execPath,['--test',...tests],{cwd:root,stdio:'inherit'});if(run.status!==0)process.exit(run.status??1);
console.log('D1 gate passed: FTS search, React navigation/lifecycle, archived recovery, last-session/scroll restoration, and exact message focusing verified.');
