import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
const root = new URL('..', import.meta.url).pathname;
const paths = ['src/runtime/database.mjs','src/runtime/projects.mjs','src/runtime/service.mjs','src/main/main.mjs','src/preload/preload.cjs','src/renderer/react/App.tsx','src/renderer/react/AddProjectModal.tsx'];
const text = Object.fromEntries(await Promise.all(paths.map(async (path) => [path, await readFile(join(root, path), 'utf8')])));
const expect=(condition,message)=>{if(!condition)throw new Error(message)};
expect(text['src/runtime/database.mjs'].includes('CREATE TABLE IF NOT EXISTS projects'),'projects table missing');
expect(text['src/runtime/database.mjs'].includes('project_id'),'session project binding missing');
expect(text['src/runtime/projects.mjs'].includes("['clone', '--'") && text['src/runtime/projects.mjs'].includes("GIT_TERMINAL_PROMPT: '0'"),'safe noninteractive clone boundary missing');
expect(text['src/runtime/projects.mjs'].includes('GITHUB_URL_CREDENTIALS') && text['src/runtime/projects.mjs'].includes('isDescendantPath'),'clone credential/containment guards missing');
expect(text['src/runtime/service.mjs'].includes("case 'project.github-clone'") && text['src/runtime/service.mjs'].includes('projectId:existing.projectId??null'),'runtime project binding missing');
expect(text['src/main/main.mjs'].includes('dialog.showOpenDialog'),'native folder picker missing');
expect(text['src/preload/preload.cjs'].includes('githubClone') && text['src/preload/preload.cjs'].includes('chooseFolder'),'project preload surface missing');
const add=text['src/renderer/react/AddProjectModal.tsx'];
for(const token of ['Local folder','GitHub URL','GitHub repositories','chooseFolder','cloneUrl','githubList','githubClone']) expect(add.includes(token),`React Add project path missing: ${token}`);
const app=text['src/renderer/react/App.tsx'];
expect(app.includes('const [draft') && app.includes('ensureActiveSession') && app.includes('window.cuppet.sessions.create(projectId)'),'first-message draft persistence missing in React');
const run=spawnSync(process.execPath,['--test','test/database-migration.test.mjs','test/database-projects.test.mjs','test/projects.test.mjs','test/runtime-project-binding.test.mjs'],{cwd:root,stdio:'inherit'});if(run.status!==0)process.exit(run.status??1);
console.log('Phase B gate passed: projects, clone/auth recovery, containment, project-bound chats, migration, and React project switching verified.');
